---
dependency:
  name: galaxy
  options:
    role-file: ${MOLECULE_PROJECT_DIRECTORY}/molecule/resources/requirements/requirements.yml

driver:
  name: docker

lint:
  name: yamllint
  options:
    config-file: molecule/resources/linter/.yamllint

platforms:
  - name: centos-6
    image: "centos:6"
    disable_cache: true
    privileged: true
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    dockerfile: ../resources/dockerfiles/Dockerfile.j2

  - name: centos-7
    image: "centos:7"
    # registry:
    #   url: "url:port"
    disable_cache: true
    privileged: true
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    command: "/usr/sbin/init"
    dockerfile: ../resources/dockerfiles/Dockerfile-systemd.j2

provisioner:
  name: ansible
  options:
    user: vagrant
  # config_options:
  #   defaults:
  #     stdout_callback: callback
  lint:
    name: ansible-lint
    options:
      c: molecule/resources/linter/.ansiblelint
  playbooks:
    converge: ../resources/playbooks/playbook-run.yml
    prepare: ../resources/playbooks/prepare-run.yml

scenario:
  name: run
  test_sequence:
    - dependency
    - lint
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy

verifier:
  name: testinfra
  directory: ../resources/tests/commun
  # additional_files_or_dirs:
  #  - ../launch/
  options:
    sudo: true
    verbose: true
    s: true
  lint:
    name: flake8
    options:
      config: molecule/resources/linter/.flake8
